### ISSUE TITLE
integration of Saltwater-Spa

### ISSUE THREAD

**Issue by red-gee** [UlrichMai/MaiPureSpaController#1]
HI, i have an saltwaterspa from intxxx, for now im experimenting with the code and hardware from Geoffroy (https://github.com/YorffoeG/diyscip), but it would be nice to control it without shift register and demuxer. 

The SaltwaterSpa has some buttons extra for Chlorination and Jet
<img width="795" alt="Bildschirmfoto 2020-06-28 um 13 35 10" src="https://user-images.githubusercontent.com/20359015/85946721-bdb7a580-b946-11ea-9b97-0808aed6ae63.png">

maybe it would be a useful....

a mashup between Geoffroy´s version and yours would be great 😉 

regards 
Gee

**Comment by UlrichMai** [comment]
@red-gee, the temperature display and led reading part is working ok? You just need the button coding?
Except for Q1 on U2 looks like my board. The connections on U1 are totally different. 
I created a branch [support-saltwaterspa](https://github.com/UlrichMai/diyscip/tree/support-saltwaterspa). Please see that branch for the changes, and let me know if it works. 
Can you tell me how the clean button works? It looks like the heater, the led is a red/green one? You press the clean button, the led goes red and after the clean phase it goes green again? Does that led change color over time, telling you must clean?
Do you know the pins, that the clean led is connected to? With this info, we can add a publisher and subscriber for the clean process.
Ulrich

**Comment by red-gee** [comment]
@UlrichMai, the clean LED is only green, when you push the cleaning-button, the display shows 003h another push will show you 005h and another 008h. When you push again, your out of menu. When cleaning starts the remaining time will be shown in 00xh in change with the temperature (hope you understand, english not my native language , boarisch liegt ma mehr 😉 )

this is the description and link I've sent Geoffroy :  
Maybe another useful information: when I push the Recovery/cleaning Button the 7segment displays shows blinking the cleaning time. First 003H when you push the button again 005H , push again it shows 008H when you wait 10 seconds the blinking stops, and the time to end of recovery would be shown in change with water temperature. 

Here is the description in the user manual 
https://www.top-poolstore.de/media/Intex-spa/handleiding/spa-bubble-jet-DE.pdf

the latest version of Geoffroy works with LED and Status and Temp. Error 91 is shown correctly, 
only control does not work, because of hardware problems on my prototyping-board.

at the moment its raining cats and dogs and I can't try it, hope it would be better next hours

Gruß
Red-gee

**Comment by red-gee** [comment]
Yesterday at 23:10 I connected „PCB v3“ on my spa...... Stable till now!

Only bubble,clean  and power buttons are missing. 
When I activate the cleaning, the temperature only shows the time till end, without temperature.   
Power, Jet and Filter button are not working.  
Themperature heatreached, Heating-Button and heating setting are working fine. 

![IMG_3272](https://user-images.githubusercontent.com/20359015/85979854-92ce5f80-b9e1-11ea-81dc-14d41b013ed2.jpg)


I can send you some states in the evening.

**Comment by UlrichMai** [comment]
1.  Are you running the ESP with 160Mhz? 
2.  I was not aware, that the display is blinking for the clean time. We need to add some code , so this is not false detected as the desired time. Will do this later. How is your programming skill? Can you propose a change?
Is that blinking faster or slower, than the blinking when you set the desired temperature? Can you point me to video, that shows these 2 blinks or make a video?
3. I am not familiar with your status screen. Do you have a log that shows pub/sub communication over time like this:
![image](https://user-images.githubusercontent.com/63186463/85986907-32451f80-b9ed-11ea-8213-98a5c271ffdb.png)
4. To detect the clean state, we need to know where the clean led is connected. It hat 2 colors. Can you please find out which pin they are connected to?
![image](https://user-images.githubusercontent.com/63186463/85986285-45a3bb00-b9ec-11ea-95a3-10f4871464f3.png)

**Comment by red-gee** [comment]
Hello,

Here are some answers,
1. Yes I think its running on 160MHz
 <img width="369" alt="Bildschirmfoto 2020-06-29 um 12 27 51" src="https://user-images.githubusercontent.com/20359015/86026892-4cecb800-ba30-11ea-9889-2a1238cff1cb.png">

2. My programming skills are Medium size, but I think it will be no Problem with a little advise from you. 
      maybe we could decide between the c and the h in the sevensegment display what information is shown.
     for me its no problem, when the display toggle between temperature and rest time, but maybe it would be a problem with Homekit.

	blinking seems to be the same. Here is the Dropbox-link to the video https://www.dropbox.com/s/foc3gj8ly5j072j/IMG_8578.MOV?dl=0

3. i will hook up my laptop to go to debug mode, then you get a list of the communication.


4. I’ve never seen the LED in other color than green, maybe its integrated, but in the last two years it was not red 😄. 
    It is no problem to find out the connection of the LED.

**Comment by red-gee** [comment]
hooking up the laptop with debug modus... results  only pressing buttons on original control panel. 

hope this helps

[spa_playing_with mqtt.txt](https://github.com/UlrichMai/MaiPureSpaController/files/4847646/spa_playing_with.mqtt.txt)
[clean 3 hours .txt](https://github.com/UlrichMai/MaiPureSpaController/files/4847647/clean.3.hours.txt)
[bubble on.txt](https://github.com/UlrichMai/MaiPureSpaController/files/4847649/bubble.on.txt)
[jet on.txt](https://github.com/UlrichMai/MaiPureSpaController/files/4847650/jet.on.txt)

**Comment by red-gee** [comment]
following the path of the clean LED
hope its will be useful
![IMG_8585](https://user-images.githubusercontent.com/20359015/86049396-656dca00-ba52-11ea-8c7a-9e55b78e837f.jpg)
![IMG_8586](https://user-images.githubusercontent.com/20359015/86049407-6868ba80-ba52-11ea-992e-560deb2e7372.jpg)
![IMG_8587](https://user-images.githubusercontent.com/20359015/86049412-6bfc4180-ba52-11ea-8f0f-a70825c7050e.jpg)
![IMG_8588](https://user-images.githubusercontent.com/20359015/86049468-81716b80-ba52-11ea-8c2c-404cb1fa42d4.jpg)
![IMG_8589](https://user-images.githubusercontent.com/20359015/86049440-74ed1300-ba52-11ea-933f-d2532473a744.jpg)
![IMG_8590](https://user-images.githubusercontent.com/20359015/86049517-93eba500-ba52-11ea-9395-5e93beb4eb09.jpg)
![IMG_8591](https://user-images.githubusercontent.com/20359015/86049526-9817c280-ba52-11ea-8686-a61584181a2b.jpg)
![IMG_8593](https://user-images.githubusercontent.com/20359015/86049534-9c43e000-ba52-11ea-9a28-aebbcd873885.jpg)
![IMG_8594](https://user-images.githubusercontent.com/20359015/86049542-9fd76700-ba52-11ea-9162-4e9c08142c7f.jpg)

**Comment by UlrichMai** [comment]
> following the path of the clean LED

I assume
U2-Q7 LED Clean Red = 0x8000
U2-Q5 LED Clean Green = 0x2000
because your `clean 3 hours .txt` is showing `spa/state => 28673` 
which is 0x7001 a combination of POWER | FILTER | LED_SELECT | CLEAN_GREEN

**Comment by UlrichMai** [comment]
@red-gee, versuch es nochmal. Es waren noch Fehler im Code,  JET konnte noch nicht tun. CLEAN Button sollte jetzt auch ausgelöst werden, aber es fehlt noch Logik um die Stunden auszuwählen. Die Stunden sollten nicht mehr als Temperatur erkannt werden. Die `QTT: subscriber wrong bool value: On` verstehe ich nicht, ist aber mein erster Kontakt mit MQTT. Wenn einige Buttons immer noch nicht funktionieren, dann musst du nochmal die Button Verbindungen zu den Pins von U1/U2 prüfen. Wenn alles nicht hilft, dann müssen wir das Timing mit dem Logic Analysator anschauen. Wenn du keinen Richtigen hast, wie ich, dann ist der für 10€ das richtige, den ich am Ende meines Readme verlinkt habe. Ulrich

**Comment by red-gee** [comment]
@UlrichMai, du bist ja fix! Danke, ich werde es gleich noch draufspielen, und tagsüber laufen lassen. Bezüglich logic Tester, ich habe ein smartscope von labnation, das dürfte sicher reichen. Die Mqtt Fehlermeldung sind immer wieder mal da, aber ich habe auch recht wenig Ahnung von Mqtt. 

Thank you for your excellent support, I will test it soon

**Comment by red-gee** [comment]
@UlrichMai 

kurzer Zwischenstand:

Jet : working
clean working

bubble: no switch in iobroker MQTT

**Comment by UlrichMai** [comment]
@red-gee, alles andere funktioniert? Super.
Bubble einschalten war im Original nicht vorgesehen. Ist bei meiner HomeKit Version auch nicht drin, weil ich mit dachte das schaltet man an wenn man im Pool sitzt, nicht remote. Ich habe es aber eingebaut. Bitte testen. Ulrich

**Comment by red-gee** [comment]
@UlrichMai 👍 

perfekt, bisher funktioniert alles.

Jet 👍 
Bubble 👍 
Power 👍 
Heat 👍 
Clean 👍 
Temp setting 👍 
outdoor temperature  👍 

was das Bubble und Jet schalten über remote betrifft, ich sehe es als option zum lüften, nach dem Cleaning.


das einzige, das ich noch festgestellt habe, ist das man den Befehl on/off  **manchmal** erst nochmal negieren muss und dann nochmal schicken, damit er angenommen wird. Kann aber auch an Iobroker liegen. ich muss das noch mal mit einem anderen MQTT Broker testen.

vielen Dank für den support!
